### ISSUE TITLE
Rehaul Edit Member Display

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/memberdb-tool#102]
## Description
Currently, we lead members to a different page when they click on a member. Instead what we want is for a modal to pop up that will have all of the member's data populated. Where those with permissions can edit specific fields just like the current [existing page](https://github.com/hack4impact-uiuc/memberdb-tool/blob/bc4a87d8517e87e05042c44a0d702821ed9b3c12/client/src/pages/Profile.jsx#L43).

![image](https://user-images.githubusercontent.com/28935000/124517355-65ad4d80-dda9-11eb-896a-92531c880cde.png)

**NOTE:** This relies on #101 where edit member modal will reside in this given location:
![image](https://user-images.githubusercontent.com/28935000/124517530-cfc5f280-dda9-11eb-8484-3f44cf4e0dcc.png)

## Learning objectives

- Modal implementations
- Working in parallel with another dev

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Research libraries or use already imported libraries that might contain ways to facilitate modal implementation
- [ ] Create a file and implement modal component 
- [ ] Connect to functions in `../utils/apiWrapper.js` 
- [ ] Once #101 is implemented create an issue or in your PR connect to new table

## Useful links

- https://react.semantic-ui.com/modules/modal/
