### ISSUE TITLE
Flexible Schema Endpoints

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/memberdb-tool#104]
## Description
Create endpoints that will support flexible schemas for non-required fields and toggle their visibility (e.g. director can add a field called “areDuesPaid” which is or isn’t visible to members of their chapter)

**Things to consider:**
- This is not only limited to the member schema, to ensure the highest code quality we want it to be versatile to other schemas that might exist like chapters and projects
- Due to the optional nature of new fields we won't have issues if they don't exist in all members or other schemas
- Frontend needs to know the new fields so that they can be displayed
- All-new optional fields must contain a viewable option (view permissions)
- Even though this is backend only while developing think of the frontend implementation too. This might save you from unnecessary endpoints or headaches

## Learning objectives

- MongoDB usage and its features

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Look over `../models/members.js` and also the provided link to familiarize yourself with schemas and helpful question
- [ ] Brainstorm endpoints that will be useful for the frontend to know about new fields (maybe a new collection?)
- [ ] Implement endpoints `../src/api/` (possibly in a new file) **bonus points if you make this not only scoped to member schema**
- [ ] Test using 

## Useful links

- https://stackoverflow.com/questions/7714216/add-new-field-to-every-document-in-a-mongodb-collection
